spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/fitness?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.chen.pojo
  mapper-locations: classpath:mybatis/mapper/*/*.xml

# 微信小程序配置
wxMini:
  appId: wx4f3009fe94aa9b8b
  secret: 6bab928a1fe80dd3a96c41d472f4ea66
